name: Clone and Package Model

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      git_url:
        description: 'Git URL to clone'
        required: true
        default: 'https://huggingface.co/immich-app/XLM-Roberta-Large-Vit-B-16Plus'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install git-lfs
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Clone Hugging Face model
      run: |
        git clone ${{ github.event.inputs.git_url }} model
        tar -czvf model.tar.gz model

    - name: Upload tar file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-tar
        path: model.tar.gz
